// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Alert struct {
	UserID    sql.NullInt64 `json:"user_id"`
	AlertType string        `json:"alert_type"`
	Coin      string        `json:"coin"`
	LastSent  sql.NullTime  `json:"last_sent"`
}

type Article struct {
	AuthorID    sql.NullInt64 `json:"author_id"`
	Type        string        `json:"type"`
	View        string        `json:"view"`
	Title       string        `json:"title"`
	Body        string        `json:"body"`
	CreatedDate sql.NullTime  `json:"created_date"`
	UpdatedDate sql.NullTime  `json:"updated_date"`
}

type Subscription struct {
	ID              int32         `json:"id"`
	UserID          sql.NullInt64 `json:"user_id"`
	Type            string        `json:"type"`
	SubscribeDate   sql.NullTime  `json:"subscribe_date"`
	CancelDate      sql.NullTime  `json:"cancel_date"`
	RenewDate       sql.NullTime  `json:"renew_date"`
	TerminationDate sql.NullTime  `json:"termination_date"`
	NextChargeDate  sql.NullTime  `json:"next_charge_date"`
}

type User struct {
	ID          int32        `json:"id"`
	FirstName   string       `json:"first_name"`
	FullName    string       `json:"full_name"`
	LastName    string       `json:"last_name"`
	AccountType string       `json:"account_type"`
	CreatedDate sql.NullTime `json:"created_date"`
	UpdatedDate sql.NullTime `json:"updated_date"`
}
