// Code generated by sqlc. DO NOT EDIT.
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  first_name,
  full_name,
  last_name,
  account_type
) VALUES (
  $1, $2, $3, $4
) RETURNING id, first_name, full_name, last_name, account_type, created_date, updated_date
`

type CreateUserParams struct {
	FirstName   string `json:"first_name"`
	FullName    string `json:"full_name"`
	LastName    string `json:"last_name"`
	AccountType string `json:"account_type"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FirstName,
		arg.FullName,
		arg.LastName,
		arg.AccountType,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.FullName,
		&i.LastName,
		&i.AccountType,
		&i.CreatedDate,
		&i.UpdatedDate,
	)
	return i, err
}
